### ISSUE TITLE
Handle the preference not being set

### ISSUE THREAD

**Issue by grahamgilbert** [groob/mackit#1]
At the moment, we get a crash if the preference hasn't been set - this should probably return either `nil` or let us set a default value.

**Comment by groob** [comment]
I set the `CFTypeID` to `Null` if I get a `nil` key. This prevents the panic and allows you to check the returns with `CFTypeID() !=Null`. 
Calling `String()` on the return won't panic now, but will give you an empty string. 

Is #2 good for now?
